apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: muneeb-finale  # Replace with your Kubernetes namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewogICAgICAgICJ1c2VybmFtZSI6ICJtdW5lZWJzaG91a2F0IiwKICAgICAgICAicGFzc3dvcmQiOiAiUmFobWFuOTkwMCIsCiAgICAgICAgImF1dGgiOiAiYlhWdVpXVmljMmh2ZFd0aGREcFNZV2h0WVc0NU9UQXciCiAgICAgIH0KICAgIH0KICB9CiAg
