apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.metadata.labels }}
    chart: {{ .Values.metadata.chart }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels }}
      chart: {{ .Values.metadata.chart }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels }}
        chart: {{ .Values.metadata.chart }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          