
replicaCount: 1
metadata:
  name: dev-pod
  labels: nginx
  chart: dev-chart
image:
  repository: "muneebshoukat/webapp" 
  tag: "latest"
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: dockerhub-secret
service:
  name: dev-svc
  labels: dev-svc
  type: ClusterIP
  port: 85
  
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
