
replicaCount: 1
metadata:
  name: nginx-pod
  labels: nginx
  chart: first-chart
image:
  repository: "muneebshoukat/test" 
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  name: nginx-svc
  labels: staging-svc
  type: ClusterIP
  port: 80
  
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
